version: '3.6'
services:
  streamlit:
    image: 316211033416.dkr.ecr.ap-south-1.amazonaws.com/streamlit:latest
    container_name: streamlit
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - "8501:8501"
